import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative, resolve, sep } from 'node:path';
const root=resolve(import.meta.dirname,'..'),out=resolve(root,process.argv[2]||'_site'),docsRoot=join(root,'docs');
const escapeHtml=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]);
const inline=source=>escapeHtml(source).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/!\[([^\]]*)\]\(([^ )]+)(?: "([^"]*)")?\)/g,'<img src="$2" alt="$1" title="$3">').replace(/\[([^\]]+)\]\(([^ )]+)(?: "([^"]*)")?\)/g,'<a href="$2" title="$3">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*(?!\*)/g,'<em>$1</em>');
function parseFrontmatter(source){const match=source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);if(!match)return{attributes:{},body:source};const attributes={};for(const line of match[1].split(/\r?\n/)){const separator=line.indexOf(':');if(separator<0)continue;const key=line.slice(0,separator).trim();let value=line.slice(separator+1).trim().replace(/^['"]|['"]$/g,'');if(value.startsWith('[')&&value.endsWith(']'))value=value.slice(1,-1).split(',').map(item=>item.trim().replace(/^['"]|['"]$/g,'')).filter(Boolean);attributes[key]=value}return{attributes,body:source.slice(match[0].length)}}
function markdown(source){const lines=source.replace(/\r/g,'').split('\n'),output=[];let paragraph=[],listType='',code=false,codeLang='',codeLines=[];const flushParagraph=()=>{if(paragraph.length)output.push(`<p>${inline(paragraph.join(' '))}</p>`);paragraph=[]};const closeList=()=>{if(listType)output.push(`</${listType}>`);listType=''};const flushCode=()=>{output.push(`<pre><code${codeLang?` class="language-${escapeHtml(codeLang)}"`:''}>${escapeHtml(codeLines.join('\n'))}</code></pre>`);codeLines=[];codeLang=''};for(const line of lines){const fence=line.match(/^```\s*(.*)$/);if(fence){if(code){flushCode();code=false}else{flushParagraph();closeList();code=true;codeLang=fence[1].trim()}continue}if(code){codeLines.push(line);continue}const heading=line.match(/^(#{1,4})\s+(.+)$/);if(heading){flushParagraph();closeList();const level=heading[1].length,text=heading[2],id=text.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'');output.push(`<h${level} id="${escapeHtml(id)}">${inline(text)}</h${level}>`);continue}const item=line.match(/^\s*([-*+] |\d+\. )(.+)$/);if(item){flushParagraph();const nextType=/\d/.test(item[1][0])?'ol':'ul';if(listType!==nextType){closeList();listType=nextType;output.push(`<${listType}>`)}output.push(`<li>${inline(item[2])}</li>`);continue}if(/^>\s?/.test(line)){flushParagraph();closeList();output.push(`<blockquote>${inline(line.replace(/^>\s?/,''))}</blockquote>`);continue}if(/^\s*([-*_])\1\1+\s*$/.test(line)){flushParagraph();closeList();output.push('<hr>');continue}if(!line.trim()){flushParagraph();closeList();continue}paragraph.push(line.trim())}if(code)flushCode();flushParagraph();closeList();return output.join('\n')}
async function findMarkdown(directory){const found=[];try{for(const entry of await readdir(directory,{withFileTypes:true})){if(entry.name.startsWith('.'))continue;const path=join(directory,entry.name);if(entry.isDirectory())found.push(...await findMarkdown(path));else if(extname(entry.name).toLowerCase()==='.md')found.push(path)}}catch(error){if(error.code!=='ENOENT')throw error}return found}
function articlePage(doc,content){return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="${escapeHtml(doc.description)}"><meta name="theme-color" content="#f5f5f7">
  <title>${escapeHtml(doc.title)} — Macaber</title><link rel="stylesheet" href="/assets/styles.css">
  <script>try{document.documentElement.dataset.theme=localStorage.getItem('theme')||'light'}catch(e){}</script>
</head>
<body>
  <header class="site-header shell"><a class="brand" href="/"><span class="brand-mark">M</span><span>Macaber</span></a><nav><a href="/#about">关于</a><a href="/#docs">文档</a><a href="https://github.com/Macaber" target="_blank" rel="noreferrer">GitHub ↗</a></nav><button class="icon-button theme-toggle" type="button" aria-label="切换主题"><span>◐</span></button></header>
  <main><header class="article-header shell"><a class="back-link" href="/#docs">← 返回文档目录</a><p class="eyebrow">${escapeHtml(doc.date||'随笔')}</p><h1>${escapeHtml(doc.title)}</h1>${doc.description?`<p class="article-deck">${escapeHtml(doc.description)}</p>`:''}<div class="article-meta"><span>${doc.readingTime} 分钟阅读</span><span>${doc.tags.map(escapeHtml).join(' · ')}</span></div></header><div class="article-layout shell"><aside class="article-aside">文档<br>${escapeHtml(doc.source)}<br><br>最后更新<br>${escapeHtml(doc.date||'—')}</aside><article class="prose">${content}</article></div></main>
  <footer class="site-footer shell"><a class="footer-brand" href="/">Macaber</a><p>用好奇心设计与构建。</p><p>© <span data-year></span> Macaber</p><a href="#">返回顶部 ↑</a></footer><script src="/assets/app.js" defer></script>
</body></html>`}
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp(join(root,'assets'),join(out,'assets'),{recursive:true});
const documents=[];for(const file of await findMarkdown(docsRoot)){const source=await readFile(file,'utf8'),{attributes,body}=parseFrontmatter(source),relativePath=relative(docsRoot,file).split(sep).join('/'),slug=relativePath.replace(/\.md$/i,'').replace(/\/index$/i,''),title=attributes.title||body.match(/^#\s+(.+)$/m)?.[1]||slug.split('/').at(-1).replace(/[-_]/g,' '),plain=body.replace(/```[\s\S]*?```/g,'').replace(/[#>*_`\[\]()!-]/g,' ').replace(/\s+/g,' ').trim();const doc={title,description:attributes.description||plain.slice(0,110),date:attributes.date||'',tags:Array.isArray(attributes.tags)?attributes.tags:attributes.tags?String(attributes.tags).split(',').map(tag=>tag.trim()):[],url:`/docs/${encodeURI(slug)}/`,source:`docs/${relativePath}`,readingTime:Math.max(1,Math.ceil(plain.length/400))};documents.push(doc);const destination=join(out,'docs',slug,'index.html');await mkdir(dirname(destination),{recursive:true});await writeFile(destination,articlePage(doc,markdown(body)))}
documents.sort((a,b)=>(b.date||'').localeCompare(a.date||'')||a.title.localeCompare(b.title,'zh-CN'));const homepage=(await readFile(join(root,'index.html'),'utf8')).replace('__DOCS_DATA__',JSON.stringify(documents).replace(/</g,'\\u003c'));await writeFile(join(out,'index.html'),homepage);await writeFile(join(out,'404.html'),homepage);await writeFile(join(out,'.nojekyll'),'');console.log(`Built ${documents.length} document(s) into ${relative(root,out)}/`);
